// LOCALHOST
### Get all workouts
GET http://localhost:8080/workouts

### Get all exercises
GET http://localhost:8080/exercises

### Get one workout
GET http://localhost:8080/workouts/

### Get one exercise
GET http://localhost:8080/exercises/

### Create workout
POST http://localhost:8080/workouts HTTP/1.1
content-type: application/json

{
    "firstName": "Cedar",
    "lastName": "Coombs",
    "email": "awesomedude5326@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "11/02/2007"
}

### Create exercise
POST http://localhost:8080/exercises HTTP/1.1
content-type: application/json

{
    "firstName": "Cedar",
    "lastName": "Coombs",
    "email": "awesomedude5326@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "11/02/2007"
}

### Update workout
PUT http://localhost:8080/workouts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Lily",
    "lastName": "Weber",
    "email": "lilyweber@gmail.com",
    "favoriteColor": "Pink",
    "birthday": "08/02/2023"
}

### Update exercise
PUT http://localhost:8080/exercises/ HTTP/1.1
content-type: application/json

{
    "firstName": "Lily",
    "lastName": "Weber",
    "email": "lilyweber@gmail.com",
    "favoriteColor": "Pink",
    "birthday": "08/02/2023"
}

### Delete workout
DELETE http://localhost:8080/workouts/ HTTP/1.1

### Delete exercise
DELETE http://localhost:8080/exercises/ HTTP/1.1



// PRODUCTION Deploy
### Get all workouts
GET https://web-services-w05-1p8w.onrender.com/workouts 

### Get all exercises
GET https://web-services-w05-1p8w.onrender.com/exercises

### Get one workout
GET https://web-services-w05-1p8w.onrender.com/workouts/

### Get one exercise
GET https://web-services-w05-1p8w.onrender.com/exercises/

### Create workout
POST https://web-services-w05-1p8w.onrender.com/workouts HTTP/1.1
content-type: application/json

{

}

### Create exercise
POST https://web-services-w05-1p8w.onrender.com/exercises HTTP/1.1
content-type: application/json

{
   
}

### Update workout
PUT https://web-services-w05-1p8w.onrender.com/workouts/ HTTP/1.1
content-type: application/json

{

}

### Update exercise
PUT https://web-services-w05-1p8w.onrender.com/exercises/ HTTP/1.1
content-type: application/json

{
  
}

### Delete workout
DELETE https://web-services-w05-1p8w.onrender.com/workouts/ HTTP/1.1

### Delete exercise
DELETE https://web-services-w05-1p8w.onrender.com/exercises/ HTTP/1.1